name: Enrich Suburb Data and Build Hugo Site

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    - cron: '0 * * * *' # Run hourly (at the start of the hour)

jobs:
  enrich_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # Check out the code including full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed to compare changes correctly
        token: ${{ secrets.PAT_TOKEN }} # Use PAT for commit/push permissions

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai python-frontmatter PyYAML python-dotenv

    - name: Run enrichment script
      run: |
        python enrich_suburb.py

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo site
      run: |
        hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public