name: Enrich Suburb Data and Build Hugo Site

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    - cron: '0 * * * *' # Run hourly (at the start of the hour)

jobs:
  enrich_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # Check out the code including full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed to compare changes correctly
        token: ${{ secrets.PAT_TOKEN }} # Use PAT for commit/push permissions

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai python-frontmatter PyYAML python-dotenv

    - name: Run enrichment script and commit changes
      run: |
        # Run the enrichment script
        python enrich_suburb.py

        # Configure Git user for commit
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Stage all changes
        git add -A

        # Commit changes if there are any
        if ! git diff --staged --quiet; then
          echo "Changes detected. Committing to main branch..."
          git commit -m "Auto-enrich suburb data [skip ci]"
          git push origin main
        else
          echo "No changes detected by the enrichment script."
        fi

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo site
      run: |
        hugo --minify

    - name: Disable Jekyll
      run: echo > public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public